### ISSUE TITLE
Add support for special characters

### ISSUE THREAD

**Issue by A1bi** [salesking/sepa_king#53]
Support for _some_ special characters like German umlauts seems to have been added with SEPA 2.7.
sepa_king still replaces or even removes special characters in any given string. Shouldn't this limitation be removed? The use of `i18n_transliterate` and the resulting replacement of all umlauts is bugging me the most.

**Comment by ledermann** [comment]
@A1bi Do you really mean v2.7? This version is from 2013. But even in the docs for the upcoming v3.0 I don't find any changes about the allowed string characters. German Umlauts are still not allowed.
Where did you read about such a change?
The main source I'm consulting is http://www.ebics.de/index.php?id=77

**Nevertheless:** The standard is a moving target. Should we always support the latest release or should we support multiple releases simultaneous? The latter would require some bigger changes to the code, so I prefer to support only the latest release. Any thoughts?

**Comment by A1bi** [comment]
Unfortunately I cannot find the page where I read that support has been added with 2.7.

But doesn't [this document](http://www.ebics.de/index.php?eID=tx_nawsecuredl&u=0&g=0&t=1467319715&hash=85f9ea11074361ffda7b255612422828d5692757&file=/fileadmin/unsecured/anlage3/anlage3_spec/Anlage_3_Datenformate_V3.0.pdf) (_Anlage 3 Datenformate V3.0_) say on page 22 that banks (at least in Germany) are **required to accept** the listed special characters and **replacement is not mandatory**. I think the table is just a recommendation for replacements if you wish to do so or if have to because your bank doesn't accept those characters.

So wouldn't it be feasible to offer at least a configurable option to disable umlaut replacement in case you are sure your bank accepts those (which I am because I already tried).

**Comment by ledermann** [comment]
You are right. After some further investigations I found the document where the change of allowed characters by v2.7 is described: 

http://www.ebics.de/fileadmin/unsecured/anlage3/anlage3_archiv/Anlage3_Archiv_V2_7.zip (see file `FS-13-02_SEPA-Zeichen.pdf`)

This means, the paragraph you described exists since v2.7 and the additional characters (umlauts and some others) are allowed.

IMHO, removing the transliteration and drop support for v2.6 would be a a clean and simple solution. Commit will follow...

**Comment by A1bi** [comment]
Works great, thanks a lot! :simple_smile:
